CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('ADMIN', 'USER') DEFAULT 'USER',
  status ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE'
);

CREATE TABLE students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(255) NOT NULL,
  prenom VARCHAR(255) NOT NULL,
  numero_inscription VARCHAR(255) NOT NULL UNIQUE,
  niveau ENUM('L1', 'L2', 'L3', 'M1', 'M2') NOT NULL,
  parcours VARCHAR(255),
  mention VARCHAR(255),
  statut VARCHAR(100) NOT NULL,
  sexe ENUM('HOMME', 'FEMME') NOT NULL
);
